export const actionType = {
   
   // LOGIN & REGISTER
   LOGIN_SUCCESS:"LOGIN_SUCCESS",  
   LOGIN_FAIL:"LOGIN_FAIL",  
   REGISTER_SUCCESS:"REGISTER_SUCCESS",  
   REGISTER_FAIL:"REGISTER_FAIL",  
   LOGOUT:'LOGOUT',

   // USER
   USER_DATA_SUCESS:"USER_DATA_SUCESS",    
   USER_DATA_FAIL:"USER_DATA_FAIL",    

   //
   POST_DATA_SUCCESS: "POST_DATA_SUCCESS",
   POST_DATA_FAIL: "POST_DATA_FAIL",

   // 
   SEARCH_SUCESS:'SEARCH_SUCCESS',
   SEARCH_ERROR:'SEARCH_ERROR',

   //
   GET_USER_CURRNET_DATA_SUCCESS : "GET_USER_CURRNET_DATA_SUCCESS",
   GET_USER_CURRNET_DATA_FAIL : "GET_USER_CURRNET_DATA_FAIL",
   
   // DELETE
   DELETE_NEW_SUCCESS : "DELETE_NEW_SUCCESS",
   DELETE_NEW_FAIL : "DELETE_NEW_FAIL",

}